version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "E:/Workspace/Volumes/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - monitoring
    ports:
      - 9090:9090
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    container_name: api
    restart: unless-stopped
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - E:/Workspace/Volumes/grafana-data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  grafana-data:
    driver: local

networks:
  monitoring:
    driver: bridge
